### ISSUE TITLE
Cannot find the Autorewrite button

### ISSUE THREAD

**Issue by diploux** [BradPerbs/GPT-Rewriter#1]
Hi,
Testing out the plugin. When I add a draft post, I'm not seeing the rewrite option anywhere in the editor. Where would I find it? 
Thanks.

**Comment by BradPerbs** [comment]
Hi @diploux , that's because there is no button inside the article. the only button to run the autorewriting is inside the plugin settings page.

The button to rewrite an article inside the page of the article itself it's an idea tho.
